on: [push]

name: CI

jobs:
  build:
    name: Test, build, and format checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Test
        run: go test ./...
      - name: Build
        run: go build main.go
      - name: Format
        run: go fmt ./... ; diff=$(git diff --compact-summary --exit-code) ; [[ -z diff ]] || (echo "format your code with `go fmt ./...`." ; exit 1)
