on: [push]

name: CI

jobs:
  build:
    name: Test, build, and format checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Test
        run: go test ./internal/...
      - name: Build
        run: go build ./cmd/app.go
      - name: Format
        run: |
          diff=$(gofmt -e -d .); \
          [[ -z $diff ]] || (echo ; echo "Reformat your code with \"gofmt -w .\"" ; exit 1)
