on: [push]

name: CI

jobs:
  build:
    name: Test and build Go binary for Locker Registration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Test
        run: go test ./...
      - name: Build
        run: go build main.go
